In [2]:
import h5py
import numpy

# FILENAME = 'seq20.h5'
# Edit the shape here:
# T = 20#10
# N = 1 #16

# FILENAME = 'seq8_8_2.h5'# prediction 8 frames with N = 2
# FILENAME = 'seq8_8_1.h5'# prediction 8 frames with N = 1
FILENAME = 'seq4.h5'# prediction 8 frames with N = 128
# Edit the shape here:
# T = 16#8-frames input, 8-frames prediction
T = 10#
N = 4

# My sequence indicators
indicators = numpy.ones((T,N))
print indicators.dtype
print indicators.shape

for i in range(0,N):
  indicators[0][i] = 0
print indicators[0:20]
# print indicators[20:30]

# Open an HDF5 file
h5file = h5py.File( FILENAME, 'w')

# Set Sequence indicator
dataset = h5file.create_dataset('sequence', shape=indicators.shape, dtype=indicators.dtype)
dataset[:] = indicators

h5file.close()


float64
(10, 4)
[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
